//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_KTPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganhHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NganhHang()
        {
            this.LoaiSPs = new HashSet<LoaiSP>();
        }
    
        public int maNganh { get; set; }
        public string tenNganh { get; set; }
        public string ghiChu { get; set; }
        public string hinhDD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiSP> LoaiSPs { get; set; }
    }
}
