//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_KTPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public string soTB { get; set; }
        public string TKQT { get; set; }
        public string TKTV { get; set; }
        public string chuDe { get; set; }
        public string noiDung { get; set; }
        public Nullable<System.DateTime> ngayTB { get; set; }
        public string trangThai { get; set; }
    
        public virtual TaiKhoanTV TaiKhoanTV { get; set; }
        public virtual TaiKhoanTV TaiKhoanTV1 { get; set; }
    }
}
